---
title: "Quarto part 2_online"
author: "Emily C Rutkowski"
format: html
knitr: 
  opts_chunk: 
    fig.path: "../output/" # added ../ because qmd is in scripts folder 
---

# Introduction

Today, we are learning about how to work with figures.

# Load the libraries

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(here)
library(palmerpenguins)
library(kableExtra)

```

# Make a plot
```{r}
#| warning: false 
#| out-width: "70%"
#| fig-align: "center"
#| label: fig-Penguin #is unique label for figure, cannot have space after - or fig cap doesnt work 
#| fig-cap: "This is a figure showing bill length by bill depth"
penguins %>%
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species ))+
  geom_point() 
```

When you look at @fig-Penguin we can see there is a positive relationship between bill length and bill depth. 

| Time  | Session | Topic    |
|:------|:-------:|---------:|
| _left_ | _center_| _right_ |
| 01:00  | 1       | Anatomy |
| 01:50  |         | *Break* |
| 02:00  | 2       | Tables  |
| 02:45  |         | *Break* |

```{r}
#| label: tbl-penguin # no space after - 
#| tbl-cap: "My awesome penguin table"
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% # make it a kable table 
  kable_classic() %>% # theme 
  row_spec(2, bold = TRUE, color = "white", background = "red") %>% # edit specific rows
  kable_styling(full_width = FALSE) # change width of table 

```

@tbl-penguin has information on the mean bill length by species. 
